kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: localhost:5000/kube-spring-cloud-cass/service-registry
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: service-registry
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      nodePort: 30000
  selector:
    app: service-registry